/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Datos.DAlmacen;
import Datos.DDetalleRecibos;
import Datos.DRecibos;
import Logica.LAlmacen;
import Logica.LDetalleRecibos;
import Logica.LRecibos;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kikin
 */
public class FrmRecibos extends javax.swing.JInternalFrame {

    DefaultTableModel miModelo;

    /**
     * Creates new form FrmRecibos
     */
    public FrmRecibos() {
        initComponents();
        habilitar(true);

        txtTotal.setEditable(false);
        miModelo = (DefaultTableModel) tblRecibos.getModel();

        tblRecibos.getColumn("CODIGO").setWidth(15);
        tblRecibos.getColumn("CODIGO").setPreferredWidth(15);

        tblRecibos.getColumn("DESCRIPCION").setWidth(220);
        tblRecibos.getColumn("DESCRIPCION").setPreferredWidth(220);

        tblRecibos.getColumn("CANTIDAD").setWidth(20);
        tblRecibos.getColumn("CANTIDAD").setPreferredWidth(20);

        tblRecibos.getColumn("U/MEDIDA").setWidth(20);
        tblRecibos.getColumn("U/MEDIDA").setPreferredWidth(20);

        tblRecibos.getColumn("P/UNITARIO").setWidth(20);
        tblRecibos.getColumn("P/UNITARIO").setPreferredWidth(20);

        tblRecibos.getColumn("TOTAL").setWidth(20);
        tblRecibos.getColumn("TOTAL").setPreferredWidth(20);

        tblRecibos.getColumn("LINEA").setWidth(20);
        tblRecibos.getColumn("LINEA").setPreferredWidth(20);

    }

    public void habilitar(boolean b) {
        txtBuscar.setEnabled(!b);
        txtFecha.setEnabled(!b);
        btnCancelar.setEnabled(!b);
        btnGuardar.setEnabled(!b);
        btnNuevo.setEnabled(b);
        txtRecibe.setEnabled(!b);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRecibe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecibos = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblPersonaE = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recibos"));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha");

        tblRecibos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD", "P/UNITARIO", "U/MEDIDA", "LINEA", "TOTAL", "IdLinea"
            }
        ));
        tblRecibos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblRecibosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecibos);
        if (tblRecibos.getColumnModel().getColumnCount() > 0) {
            tblRecibos.getColumnModel().getColumn(7).setMinWidth(0);
            tblRecibos.getColumnModel().getColumn(7).setPreferredWidth(0);
            tblRecibos.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        jLabel2.setText("Persona Recibe:");

        jLabel3.setText("Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRecibe)
                            .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPersonaE, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnNuevo)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblPersonaE, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRecibe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String msgfinal = "";
        if (txtRecibe.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Campo persona recibe obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtRecibe.requestFocusInWindow();
            return;
        }

        if (txtFecha.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "Campo fecha obligatorio", "Validación", JOptionPane.WARNING_MESSAGE);
            txtFecha.requestFocusInWindow();
            return;
        }

        LRecibos fn = new LRecibos();
        DRecibos dts = new DRecibos();

        Calendar cal;

        cal = txtFecha.getCalendar();

        int aa, mm, dd;

        aa = cal.get(Calendar.YEAR) - 1900;
        mm = cal.get(Calendar.MONTH);
        dd = cal.get(Calendar.DAY_OF_MONTH);

        dts.setFechaRecibo(new Date(aa, mm, dd));
        dts.setPersonaEntrega(lblPersonaE.getText());
        dts.setPersonaRecibe(txtRecibe.getText());

        int idrec = fn.insertarRecibos(dts);
        if (idrec > 0) {
            int filas = tblRecibos.getRowCount();
            for (int i = 0; i < filas; i++) {

                String idprod = tblRecibos.getValueAt(i, 0).toString();
                int idlinea = Integer.parseInt(tblRecibos.getValueAt(i, 7).toString());
                int cantidad = Integer.parseInt(tblRecibos.getValueAt(i, 2).toString());
                double total = Double.parseDouble(tblRecibos.getValueAt(i, 6).toString());
                
                LDetalleRecibos fundf = new LDetalleRecibos();
                DDetalleRecibos dtsf = new DDetalleRecibos();
                dtsf.setRecibosId(idrec);
                //ertar_datellerecib(in recibid int, in prodid varchar(45), in idlin int, in cant int, in tot decimal(18,2))
                dtsf.setProductosId(idprod);
                dtsf.setLineasId(idlinea);
                dtsf.setCantidad(cantidad);
                dtsf.setTotal(total);
                String mensaje = fundf.registrarDetalleRecibos(dtsf);
                
                  if (mensaje.equals("si")) {
                    LAlmacen funAl = new LAlmacen();
                    DAlmacen dtsp = new DAlmacen();

                    dtsp.setIdAlmacen(idprod);
                    dtsp.setStock(cantidad);
                  

                    msgfinal = funAl.disminuirStock(dtsp);

                }

            }
            JOptionPane.showMessageDialog(rootPane, msgfinal, "Información", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Ocurio un problema al insertar", "Información", JOptionPane.ERROR_MESSAGE);
        }
        limpiar();
        habilitar(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boolean b = estaenTabla(txtBuscar.getText());
            if (b == false) {
                mostrarProductos(txtBuscar.getText());
            }
            sumarTotal();
            txtBuscar.setText("");
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void tblRecibosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblRecibosKeyPressed
        // TODO add your handling code here:
        DecimalFormat ft = new DecimalFormat("####.00");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            for (int i = 0; i < tblRecibos.getRowCount(); i++) {
                int cantidad = Integer.parseInt(tblRecibos.getValueAt(i, 2).toString());
                double preciounitario = Double.parseDouble(tblRecibos.getValueAt(i, 3).toString());

                double totalparcial = cantidad * preciounitario;
                tblRecibos.setValueAt(ft.format(totalparcial), i, 6);
            }
            sumarTotal();
        }

    }//GEN-LAST:event_tblRecibosKeyPressed
    public boolean estaenTabla(String texto) {
        boolean res = false;
        DecimalFormat ft = new DecimalFormat("####.00");
        for (int i = 0; i < tblRecibos.getRowCount(); i++) {
            String codigo = tblRecibos.getValueAt(i, 0).toString();
            if (codigo.equals(texto)) {
                int cantidad = Integer.parseInt(tblRecibos.getValueAt(i, 2).toString());
                double preciounitario = Double.parseDouble(tblRecibos.getValueAt(i, 3).toString());
                int totalcantidad = cantidad + 1;
                tblRecibos.setValueAt(totalcantidad, i, 2);

                double totalparcial = totalcantidad * preciounitario;
                tblRecibos.setValueAt(ft.format(totalparcial), i, 6);
                res = true;
            }
        }
        sumarTotal();
        return res;
    }

    public void sumarTotal() {
        DecimalFormat ft = new DecimalFormat("####.00");
        double totalparcial = 0, totalfinal = 0;
        for (int i = 0; i < tblRecibos.getRowCount(); i++) {
            totalparcial = Double.parseDouble(tblRecibos.getValueAt(i, 6).toString());
            totalfinal += totalparcial;
            txtTotal.setText(ft.format(totalfinal));
        }

    }

    public void mostrarProductos(String producto) {
        LAlmacen fn = new LAlmacen();
        DAlmacen dts = new DAlmacen();
        DefaultTableModel tblDatos = (DefaultTableModel) tblRecibos.getModel();
        dts.setIdAlmacen(producto);
        String registros[] = fn.mostrarbuscarProductosRec(dts);
        if (registros[0] != null) {
            tblDatos.insertRow(0, registros);
            tblRecibos.setModel(tblDatos);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Producto no existen en el inventario, favor de validar");
        }

    }

    public void limpiar() {
        txtRecibe.setText("");
        txtBuscar.setText("");
        txtFecha.setDate(null);
        txtTotal.setText("");
        try {
            DefaultTableModel modelo = (DefaultTableModel) tblRecibos.getModel();
            int filas = tblRecibos.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPersonaE;
    private javax.swing.JTable tblRecibos;
    private javax.swing.JTextField txtBuscar;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtRecibe;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    public void setUsuario(String personae) {
       lblPersonaE.setText(personae);
    }
}
